version: "3"
services:
  postgres:
    restart: always
    image: postgres:9.6.2-alpine
    container_name: my-pg-test-db
    volumes:
      - ./data/db/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: my-db
      POSTGRES_DB: my-db